registryItems:
  applications:
  - {postgresql-scenario: nq 0}
  instances:
  - {postgresql-scenario: 1}
  operationNames:
  - postgresql-scenario: [/postgresql-scenario/case/postgres]
segmentItems:
- applicationCode: postgresql-scenario
  segmentSize: ge 1
  segments:
    - segmentId: not null
      spans:
        -
          operationName: PostgreSQL/JDBI/PreparedStatement/execute
          operationId: eq 0
          parentSpanId: 0
          spanId: 1
          tags: 
          - {key: "db.type", value: "sql"}
          - {key: "db.instance", value: "postgres"}
          - {key: "db.statement", value: "CREATE TABLE test_007(\nid VARCHAR(1) PRIMARY KEY, \nvalue VARCHAR(1) NOT NULL)"}
          logs: []
          startTime: nq 0
          endTime: nq 0
          isError: false
          spanLayer: Database
          spanType: Exit
          componentName: null
          componentId: 37
          peer: postgresql-server:5432
          peerId: eq 0
        -
          operationName: PostgreSQL/JDBI/CallableStatement/execute
          operationId: eq 0
          parentSpanId: 0
          spanId: 2
          tags: 
          - {key: "db.type", value: "sql"}
          - {key: "db.instance", value: "postgres"}
          - {key: "db.statement", value: "INSERT INTO test_007(id, value) VALUES(?,?)"}
          logs: []
          startTime: nq 0
          endTime: nq 0
          isError: false
          spanLayer: Database
          spanType: Exit
          componentName: null
          componentId: 37
          peer: postgresql-server:5432
          peerId: eq 0
        -
          operationName: PostgreSQL/JDBI/Statement/execute
          operationId: eq 0
          parentSpanId: 0
          spanId: 3
          tags: 
          - {key: "db.type", value: "sql"}
          - {key: "db.instance", value: "postgres"}
          - {key: "db.statement", value: "DROP table test_007"}
          logs: []
          startTime: nq 0
          endTime: nq 0
          isError: false
          spanLayer: Database
          spanType: Exit
          componentName: null
          componentId: 37
          peer: postgresql-server:5432
          peerId: eq 0
        -
          operationName: PostgreSQL/JDBI/Connection/close
          operationId: eq 0
          parentSpanId: 0
          spanId: 4
          tags: 
          - {key: "db.type", value: "sql"}
          - {key: "db.instance", value: "postgres"}
          - {key: "db.statement", value: ""}
          logs: []
          startTime: nq 0
          endTime: nq 0
          isError: false
          spanLayer: Database
          spanType: Exit
          componentName: null
          componentId: 37
          peer: postgresql-server:5432
          peerId: eq 0
        -
          operationName: PostgreSQL/JDBI/Connection/close
          operationId: eq 0
          parentSpanId: 0
          spanId: 5
          tags: 
          - {key: "db.type", value: "sql"}
          - {key: "db.instance", value: "postgres"}
          - {key: "db.statement", value: ""}
          logs: []
          startTime: nq 0
          endTime: nq 0
          isError: false
          spanLayer: Database
          spanType: Exit
          componentName: null
          componentId: 37
          peer: postgresql-server:5432
          peerId: eq 0
        -
          operationName: /postgresql-scenario/case/postgres
          operationId: eq 0
          parentSpanId: -1
          spanId: 0
          startTime: nq 0
          endTime: nq 0
          spanLayer: Http
          isError: false
          spanType: Entry
          componentName: null
          componentId: 1
          tags:
            - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/postgresql-scenario/case/postgres'}
            - {key: http.method, value: GET}
          logs: []
          peer: null
          peerId: eq 0
