registryItems:
  applications:
  - {grpc-consumer-scenario: nq 0}
  - {grpc-provider-scenario: nq 0}
  instances:
  - {grpc-consumer-scenario: 1}
  - {grpc-provider-scenario: 1}
  operationNames:
  - grpc-consumer-scenario: [Greeter.sayHello/client/ResponseObserver/onNext, /service-consumer/case/grpc-scenario, Greeter.sayHello, Greeter.sayHello/client/ResponseObserver/onComplete]
  - grpc-provider-scenario: [Greeter.sayHello, Greeter.sayHello/server/RequestObserver/onNext, Greeter.sayHello/server/RequestObserver/onComplete]
segmentItems:
- applicationCode: grpc-consumer-scenario
  segmentSize: 4
  segments:
  - segmentId: not null
    spans:
    - operationName: Greeter.sayHello
      operationId: 0
      parentSpanId: 0
      spanId: 1
      spanLayer: RPCFramework
      startTime: nq 0
      endTime: nq 0
      componentId: 23
      componentName: ''
      isError: false
      spanType: Exit
      peer: 'provider-scenario:18080'
      peerId: 0
    - operationName: /service-consumer/case/grpc-scenario
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Http
      startTime: nq 0
      endTime: nq 0
      componentId: 1
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      tags:
      - {key: url, value: 'http://localhost:{SERVER_OUTPUT_PORT}/service-consumer/case/grpc-scenario'}
      - {key: http.method, value: GET}
  - segmentId: not null
    spans:
    - operationName: Greeter.sayHello/client/ResponseObserver/onNext
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 0
      componentName: ''
      isError: false
      spanType: Local
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /service-consumer/case/grpc-scenario, networkAddressId: 0, entryServiceId: 0, refType: CrossThread, parentSpanId: 1, parentTraceSegmentId: '${grpc-consumer-scenario[0]}', parentApplicationInstanceId: nq 0, networkAddress: '', entryServiceName: /service-consumer/case/grpc-scenario, entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: Greeter.sayHello/client/ResponseObserver/onNext
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 0
      componentName: ''
      isError: false
      spanType: Local
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /service-consumer/case/grpc-scenario, networkAddressId: 0, entryServiceId: 0, refType: CrossThread, parentSpanId: 1, parentTraceSegmentId: '${grpc-consumer-scenario[0]}', parentApplicationInstanceId: nq 0, networkAddress: '', entryServiceName: /service-consumer/case/grpc-scenario, entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: Greeter.sayHello/client/ResponseObserver/onComplete
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 0
      componentName: ''
      isError: false
      spanType: Local
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /service-consumer/case/grpc-scenario, networkAddressId: 0, entryServiceId: 0, refType: CrossThread, parentSpanId: 1, parentTraceSegmentId: '${grpc-consumer-scenario[0]}', parentApplicationInstanceId: nq 0, networkAddress: '', entryServiceName: /service-consumer/case/grpc-scenario, entryApplicationInstanceId: nq 0}
- applicationCode: grpc-provider-scenario
  segmentSize: 4
  segments:
  - segmentId: not null
    spans:
    - operationName: Greeter.sayHello
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 23
      componentName: ''
      isError: false
      spanType: Entry
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: /service-consumer/case/grpc-scenario, networkAddressId: 0, entryServiceId: 0, refType: CrossProcess, parentSpanId: 1, parentTraceSegmentId: '${grpc-consumer-scenario[0]}', parentApplicationInstanceId: nq 0, networkAddress: 'provider-scenario:18080', entryServiceName: /service-consumer/case/grpc-scenario, entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: Greeter.sayHello/server/RequestObserver/onNext
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 0
      componentName: ''
      isError: false
      spanType: Local
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: Greeter.sayHello, networkAddressId: 0, entryServiceId: 0, refType: CrossThread, parentSpanId: 1, parentTraceSegmentId: '${grpc-provider-scenario[0]}', parentApplicationInstanceId: nq 0, networkAddress: '', entryServiceName: /service-consumer/case/grpc-scenario, entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: Greeter.sayHello/server/RequestObserver/onNext
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 0
      componentName: ''
      isError: false
      spanType: Local
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: Greeter.sayHello, networkAddressId: 0, entryServiceId: 0, refType: CrossThread, parentSpanId: 1, parentTraceSegmentId: '${grpc-provider-scenario[0]}', parentApplicationInstanceId: nq 0, networkAddress: '', entryServiceName: /service-consumer/case/grpc-scenario, entryApplicationInstanceId: nq 0}
  - segmentId: not null
    spans:
    - operationName: Greeter.sayHello/server/RequestObserver/onComplete
      operationId: 0
      parentSpanId: -1
      spanId: 0
      spanLayer: Unknown
      startTime: nq 0
      endTime: nq 0
      componentId: 0
      componentName: ''
      isError: false
      spanType: Local
      peer: ''
      peerId: 0
      refs:
      - {parentServiceId: 0, parentServiceName: Greeter.sayHello, networkAddressId: 0, entryServiceId: 0, refType: CrossThread, parentSpanId: 1, parentTraceSegmentId: '${grpc-provider-scenario[0]}', parentApplicationInstanceId: nq 0, networkAddress: '', entryServiceName: /service-consumer/case/grpc-scenario, entryApplicationInstanceId: nq 0}