version: '2.1'
services:
  redis-server:
    image: redis:3.2.9-alpine
    expose:
      - "6379"

  mysql-testcase:
    image: skywalking/jedis-standalone-scenario:{CASES_IMAGE_VERSION}
    expose:
      - "18080"
    ports:
      - "18080:8080"
    environment:
      - COLLECTOR_SERVER=mock-collector:12800
      - REDIS_HOST=redis-server
    links:
      - mock-collector
      - redis-server
    volumes:
      - {AGENT_FILE_PATH}:/usr/local/tomcat/agent
    depends_on:
      - mock-collector
      - redis-server

  mock-collector:
    image: skywalking/skywalking-mock-collector:{COLLECTOR_IMAGE_VERSION}
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - "12800"
    ports:
      - "12800:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:12800/receiveData"]
      interval: 5s
      timeout: 10s
      retries: 5
