version: '2.1'
services:
  h2-testcase:
    image: skywalking/h2-scenario:{CASES_IMAGE_VERSION}
    expose:
      - "8080"
    ports:
      - "{SERVER_OUTPUT_PORT}:8080"
    environment:
      - COLLECTOR_SERVER=mock-collector:12800
    links:
      - mock-collector
    volumes:
      - {AGENT_FILE_PATH}:/usr/local/tomcat/agent
    depends_on:
      - mock-collector

  mock-collector:
    image: skywalking/skywalking-mock-collector:{COLLECTOR_IMAGE_VERSION}
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - "12800"
    ports:
      - "{COLLECTOR_OUTPUT_PORT}:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:12800/receiveData"]
      interval: 10s
      timeout: 10s
      retries: 5
