version: '2.1'
services:
  elasticsearch-server:
    image: docker.elastic.co/elasticsearch/elasticsearch:{CASES_IMAGE_VERSION}
    expose:
      - 9300
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - discovery.type=single-node

  elasticsearch-scenario:
    image: skywalking/elasticsearch-scenario:{CASES_IMAGE_VERSION}
    expose:
      - 8080
    ports:
      - "{SERVER_OUTPUT_PORT}:8080"
    environment:
      - COLLECTOR_SERVER=mock-collector:12800
      - ELASTICSEARCH_HOST=elasticsearch-server
    links:
      - mock-collector
      - elasticsearch-server
    volumes:
      - {AGENT_FILE_PATH}:/usr/local/skywalking-elasticsearch-scenario/agent
    depends_on:
      mock-collector:
        condition: service_healthy

  mock-collector:
    image: skywalking/skywalking-mock-collector:{COLLECTOR_IMAGE_VERSION}
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - 12800
    ports:
      - "{COLLECTOR_OUTPUT_PORT}:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:12800/receiveData"]
      interval: 5s
      timeout: 10s
      retries: 5