version: '2.1'
services:
  zk-server:
    image: zookeeper:3.4.10

  dubbox-consumer:
    image: skywalking/dubbox-consumer-scenario:{CASES_IMAGE_VERSION}
    expose:
      - "8080"
    ports:
      - "{SERVER_OUTPUT_PORT}:8080"
    environment:
      - COLLECTOR_SERVER=mock-collector:12800
      - ZK_ADDRESS=zk-server:2181
    links:
      - zk-server
      - dubbox-provider
      - mock-collector
    volumes:
     - {AGENT_FILE_PATH}:/usr/local/tomcat/agent
    depends_on:
      mock-collector:
        condition: service_healthy

  dubbox-provider:
    image: skywalking/dubbox-provider-scenario:{CASES_IMAGE_VERSION}
    environment:
      - COLLECTOR_SERVER=mock-collector:12800
      - ZK_ADDRESS=zk-server:2181
    expose:
      - "20880"
    volumes:
     - {AGENT_FILE_PATH}:/usr/local/dubbox-provider/agent
    links:
      - zk-server
      - mock-collector
    depends_on:
      mock-collector:
        condition: service_healthy

  mock-collector:
    image: skywalking/skywalking-mock-collector:{COLLECTOR_IMAGE_VERSION}
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - "12800"
    ports:
      - "{COLLECTOR_OUTPUT_PORT}:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:{COLLECTOR_OUTPUT_PORT}/receiveData"]
      interval: 5s
      timeout: 10s
      retries: 5
