version: '2.1'
services:
  mysql-server:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","--silent"]
      interval: 5s
      timeout: 10s
      retries: 5

  mysql-testcase:
    image: skywalking/mysql-scenario:{CASES_IMAGE_VERSION}
    expose:
      - "18080"
    ports:
      - "18080:8080"
    environment:
      - COLLECTOR_SERVER=mock-collector:12800
      - MYSQL_INSTANCE_HOST=mysql-server:3306
    links:
      - mock-collector
      - mysql-server
    volumes:
      - {AGENT_FILE_PATH}:/usr/local/tomcat/agent
    depends_on:
      - mock-collector
      - mysql-server

  mock-collector:
    image: skywalking/skywalking-mock-collector:{COLLECTOR_IMAGE_VERSION}
    environment:
      - GRPC_BIND_HOST=mock-collector
    expose:
      - "12800"
    ports:
      - "12800:12800"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:12800/receiveData"]
      interval: 10s
      timeout: 10s
      retries: 5
